// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFkgdU5uhVqlblu9WbXmxPHwZmRiNxUGk',
    appId: '1:377691344063:web:cfb21a45895426735eca0a',
    messagingSenderId: '377691344063',
    projectId: 'tolaktax',
    authDomain: 'tolaktax.firebaseapp.com',
    storageBucket: 'tolaktax.firebasestorage.app',
    measurementId: 'G-38FRLK1TPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkC68wpnkg1torzLYa2awijktb_hHBP7s',
    appId: '1:377691344063:android:1cce6005f280ed0c5eca0a',
    messagingSenderId: '377691344063',
    projectId: 'tolaktax',
    storageBucket: 'tolaktax.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgjXJIIUMe55RkwIh7ZLLQhk6UWiQ3wJ0',
    appId: '1:377691344063:ios:86c246fd1462ac8d5eca0a',
    messagingSenderId: '377691344063',
    projectId: 'tolaktax',
    storageBucket: 'tolaktax.firebasestorage.app',
    iosClientId: '377691344063-e60icdeosi8qpsbsfaqn24f00ooa21g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tolakTax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgjXJIIUMe55RkwIh7ZLLQhk6UWiQ3wJ0',
    appId: '1:377691344063:ios:86c246fd1462ac8d5eca0a',
    messagingSenderId: '377691344063',
    projectId: 'tolaktax',
    storageBucket: 'tolaktax.firebasestorage.app',
    iosClientId: '377691344063-e60icdeosi8qpsbsfaqn24f00ooa21g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tolakTax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFkgdU5uhVqlblu9WbXmxPHwZmRiNxUGk',
    appId: '1:377691344063:web:bf90da0b222c10595eca0a',
    messagingSenderId: '377691344063',
    projectId: 'tolaktax',
    authDomain: 'tolaktax.firebaseapp.com',
    storageBucket: 'tolaktax.firebasestorage.app',
    measurementId: 'G-RWQE9G9LJ2',
  );
}
